"When does __name__ == '__main__' equal True in a Python file" = [
    "When the file is run as a script",
    "When the file is imported as a module",
    "When the file has a valid name",
    "When the file only has one function",
]

"Which version of Python is the first with TOML support built in" = [
    "3.11", "3.9", "3.10", "3.12"
] 

"What's the official name of the := operator" = [
    "Assignment expression",
    "Named expression",
    "Walrus operator",
    "Colon equals operator"
]

"When was the first known use of the word 'quiz'" = [
    "1781", "1771", "1871", "1881"
]

"Which built-in function can get information from the user" = [
    "input", "get", "print", "write"
]